/* eslint-disable @typescript-eslint/naming-convention */
/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/v0/auth/token": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Login For Access Token
     * @description Handle user login and return an access token.
     *
     *     Parameters
     *     ----------
     *     form_data : OAuth2PasswordRequestForm
     *         The form data containing username and password.
     *     db : db_dep
     *         The database dependency for accessing user data.
     *
     *     Returns:
     *     -------
     *     model.Token
     *         A dictionary containing the access token and token type.
     */
    post: operations["login_for_access_token_v0_auth_token_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v0/health/running": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Check Running
     * @description Health check endpoint to verify service is running.
     */
    get: operations["check_running_v0_health_running_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v0/health/ready": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Check Ready
     * @description Health check endpoint to verify external dependencies (Readiness).
     *
     *     Checks database connectivity. Returns 503 if DB is unreachable.
     */
    get: operations["check_ready_v0_health_ready_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v0/users/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get All Users
     * @description Endpoint to retrieve a list of all users.
     *
     *     Args:
     *         db (db_dep): The database session.
     *         user_token (user_dep): The user session.
     *         response (Response): The FastAPI response object to set status codes.
     *         params (model.AllUsersQueryParams): Query parameters for filtering
     *             users.
     *
     *     Returns:
     *         PaginatedResponse[model.UserResponse]: A list of user data and
     *             pagination metadata.
     */
    get: operations["get_all_users_v0_users__get"];
    put?: never;
    /**
     * Create User
     * @description Endpoint to create a new user.
     *
     *     Args:
     *         user (model.UserCreate): The user data to create.
     *         db (db_dep): The database session.
     *         user_token (user_admin_dep): The user session with admin scope.
     *         response (Response): The FastAPI response object to set status codes.
     *
     *     Returns:
     *         model.UserResponse: The created user data.
     */
    post: operations["create_user_v0_users__post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v0/users/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get User
     * @description Endpoint to retrieve a user by their user_id.
     *
     *     Args:
     *         id (str): The unique identifier of the user.
     *         db (db_dep): The database session.
     *         user_token (user_admin_dep): The authenticated user token.
     *         response (Response): The FastAPI response object to set status codes.
     *         params (FieldSelectionParams): Query parameters for field selection.
     *
     *     Returns:
     *         model.UserResponse: The user data if found.
     */
    get: operations["get_user_v0_users__id__get"];
    /**
     * Update User
     * @description Endpoint to update an existing user's information.
     *
     *     Args:
     *         id (str): The unique identifier of the user to update.
     *         user (model.UserUpdate): The updated user data.
     *         db (db_dep): The database session.
     *         user_token (user_admin_dep): The user session with admin scope.
     *         response (Response): The FastAPI response object to set status codes.
     *
     *     Returns:
     *         model.UserResponse: The updated user data.
     */
    put: operations["update_user_v0_users__id__put"];
    post?: never;
    /**
     * Delete User
     * @description Endpoint to delete a user by their user_id.
     *
     *     Args:
     *         id (str): The unique identifier of the user to delete.
     *         db (db_dep): The database session.
     *         user_token (user_admin_dep): The user session with admin scope.
     *         response (Response): The FastAPI response object to set status codes.
     *
     *     Returns:
     *         None
     */
    delete: operations["delete_user_v0_users__id__delete"];
    options?: never;
    head?: never;
    /**
     * Patch User
     * @description Endpoint to partially update an existing user's information.
     *
     *     Args:
     *         id (str): The unique identifier of the user to update.
     *         user (model.UserPatch): The updated user data.
     *         db (db_dep): The database session.
     *         user_token (user_admin_dep): The user session with admin scope.
     *         response (Response): The FastAPI response object to set status codes.
     *
     *     Returns:
     *         model.UserResponse: The updated user data.
     */
    patch: operations["patch_user_v0_users__id__patch"];
    trace?: never;
  };
  "/v0/modules/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get All Modules
     * @description Retrieve all modules with optional filtering.
     */
    get: operations["get_all_modules_v0_modules__get"];
    put?: never;
    /**
     * Create Module
     * @description Create a new module (and initial draft version).
     */
    post: operations["create_module_v0_modules__post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v0/modules/{module_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Module
     * @description Get a specific module by ID.
     */
    get: operations["get_module_v0_modules__module_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v0/modules/{module_id}/versions": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Module Versions
     * @description Get all versions of a specific module.
     */
    get: operations["get_module_versions_v0_modules__module_id__versions_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v0/modules/versions/{version_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Version
     * @description Get details of a specific module version.
     */
    get: operations["get_version_v0_modules_versions__version_id__get"];
    /**
     * Update Version Content
     * @description Update the content of a module version (Draft/Revision only).
     *
     *     Args:
     *         version_id (uuid.UUID): The ID of the module version to update.
     *         update_data (model.ModuleVersionUpdate): The updated version data.
     *         db (db_dep): The database dependency for querying and persisting data.
     *         user_token (UserToken): Token containing information about the
     *             authenticated user.
     *
     *     Returns:
     *         model.ModuleVersionResponse: The updated module version record.
     */
    put: operations["update_version_content_v0_modules_versions__version_id__put"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v0/modules/versions/{version_id}/status": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /**
     * Update Workflow Status
     * @description Transition the workflow status of a version (e.g., Submit, Approve).
     *
     *     Args:
     *         version_id (uuid.UUID): The ID of the module version to update.
     *         status_update (model.ModuleVersionStatusUpdate): The status update data.
     *         db (db_dep): The database dependency for querying and persisting data.
     *         user_token (UserToken): Token containing information about the
     *             authenticated user.
     *
     *     Returns:
     *         model.ModuleVersionResponse: The updated module version record.
     */
    patch: operations["update_workflow_status_v0_modules_versions__version_id__status_patch"];
    trace?: never;
  };
  "/v0/modules/versions/{version_id}/translations": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Add Translation
     * @description Add a translation to a module version.
     *
     *     Args:
     *         version_id (uuid.UUID): The ID of the module version to add the
     *             translation to.
     *         translation (model.TranslationCreate): The translation data to add.
     *         db (db_dep): The database dependency for querying and persisting data.
     *         user_token (UserToken): Token containing information about the
     *             authenticated user.
     *
     *     Returns:
     *         model.TranslationResponse: The created translation record.
     */
    post: operations["add_translation_v0_modules_versions__version_id__translations_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /**
     * AuditLogResponse
     * @description Response model for audit log entries.
     *
     *     Attributes:
     *         id (uuid.UUID): Unique identifier for the audit log.
     *         action (str): Action performed.
     *         comment (str | None): Optional comment.
     *         timestamp (datetime): Timestamp of the action.
     *         user_id (str): ID of the user who performed the action.
     *         user_name (str | None): Name of the user who performed the action.
     */
    AuditLogResponse: {
      /**
       * Id
       * Format: uuid
       * @description Unique identifier for the audit log
       */
      id: string;
      /**
       * Action
       * @description Action performed
       */
      action: string;
      /**
       * Comment
       * @description Optional comment
       */
      comment?: string | null;
      /**
       * Timestamp
       * Format: date-time
       * @description Timestamp of the action
       */
      timestamp: string;
      /**
       * User Id
       * @description ID of the user who performed the action
       */
      user_id: string;
      /**
       * User Name
       * @description Name of the user who performed the action
       */
      user_name?: string | null;
    };
    /** Body_login_for_access_token_v0_auth_token_post */
    Body_login_for_access_token_v0_auth_token_post: {
      /** Grant Type */
      grant_type?: string | null;
      /** Username */
      username: string;
      /**
       * Password
       * Format: password
       */
      password: string;
      /**
       * Scope
       * @default
       */
      scope: string;
      /** Client Id */
      client_id?: string | null;
      /**
       * Client Secret
       * Format: password
       */
      client_secret?: string | null;
    };
    /**
     * Faculty
     * @description Enumeration of faculties within the application.
     *
     *     Attributes:
     *     ----------
     *     F1_MPM : str
     *         Represents FB1 the Faculty of Mechanical Engineering, Process
     *         Engineering, and Maritime Technology.
     *     F2_ELS : str
     *         Represents FB2 the Faculty of Energy and Life Sciences.
     *     F3_IC : str
     *         Represents FB3 the Faculty of Information and Communication.
     *     F4_BS : str
     *         Represents the Business School.
     *     ADMIN : str
     *         Represents administrative roles.
     * @enum {string}
     */
    Faculty:
      | "F1_MECHANICAL_PROCESS_MARITIME"
      | "F2_ENERGY_LIFE_SCIENCE"
      | "F3_INFORMATION_COMMUNICATION"
      | "F4_BUSINESS_SCHOOL"
      | "ADMIN";
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /**
     * ModuleCreate
     * @description Model for creating a module.
     *
     *     Attributes:
     *         module_number (str): Unique module number.
     *         title (str): Title of the module.
     *         content (str | None): Initial description of the module.
     *         ects (int): ECTS credits for the module.
     *         valid_from_semester (str): Semester from which the module is valid.
     */
    ModuleCreate: {
      /**
       * Module Number
       * @description Unique module number
       */
      module_number: string;
      /**
       * Title
       * @description Module title
       */
      title: string;
      /**
       * Owner Id
       * @description Owner user ID
       */
      owner_id?: string | null;
      /**
       * Content
       * @description Initial description
       */
      content?: string | null;
      /**
       * Ects
       * @description ECTS credits
       */
      ects: number;
      /**
       * Valid From Semester
       * @description Valid from semester
       */
      valid_from_semester: string;
    };
    /**
     * ModuleFields
     * @description Enumeration of fields for sorting modules.
     *
     *     Attributes:
     *         MODULE_NUMBER (str): Field for module number.
     *         TITLE (str): Field for module title.
     *         OWNER (str): Field for module owner.
     *         UPDATED_AT (str): Field for last updated timestamp.
     * @enum {string}
     */
    ModuleFields: "module_number" | "title" | "owner" | "updated_at";
    /**
     * ModuleResponse
     * @description Response model for modules.
     *
     *     Attributes:
     *         id (uuid.UUID): Unique identifier for the module.
     *         owner_id (str | None): Owner user ID.
     *         current_version (ModuleVersionResponse | None): Current module version.
     */
    ModuleResponse: {
      /**
       * Module Number
       * @description Unique module number
       */
      module_number: string;
      /**
       * Title
       * @description Module title
       */
      title: string;
      /**
       * Id
       * Format: uuid
       * @description Unique identifier for the module
       */
      id: string;
      /**
       * Owner Id
       * @description Owner user ID
       */
      owner_id?: string | null;
      /** @description Current module version */
      current_version?: components["schemas"]["ModuleVersionResponse"] | null;
      /** @description Latest released module version */
      released_version?: components["schemas"]["ModuleVersionResponse"] | null;
    };
    /**
     * ModuleVersionResponse
     * @description Response model for module versions.
     *
     *     Attributes:
     *         id (uuid.UUID): Unique identifier for the module version.
     *         module_id (uuid.UUID): Associated module ID.
     *         status (WorkflowStatus): Current workflow status of the module version.
     *         updated_at (datetime): Timestamp of the last update.
     *         last_editor_id (str | None): ID of the last editor.
     *         translations (list[TranslationResponse]): List of translations.
     *         audit_logs (list[AuditLogResponse]): List of audit log entries.
     *         content (str | None): Content of the module version.
     *         ects (int | None): ECTS credits for the module version.
     *         valid_from_semester (str): Semester from which the module version is
     *             valid.
     */
    ModuleVersionResponse: {
      /**
       * Content
       * @description Module version content
       */
      content?: string | null;
      /**
       * Ects
       * @description ECTS credits
       */
      ects?: number | null;
      /**
       * Valid From Semester
       * @description e.g. 'WiSe 2025/26'
       */
      valid_from_semester: string;
      /**
       * Id
       * Format: uuid
       * @description Unique identifier for the module version
       */
      id: string;
      /**
       * Module Id
       * Format: uuid
       * @description Associated module ID
       */
      module_id: string;
      /** @description Current workflow status of the module version */
      status: components["schemas"]["WorkflowStatus"];
      /**
       * Updated At
       * Format: date-time
       * @description Timestamp of the last update
       */
      updated_at: string;
      /**
       * Last Editor Id
       * @description ID of the last editor
       */
      last_editor_id?: string | null;
      /**
       * Translations
       * @description List of translations
       */
      translations?: components["schemas"]["TranslationResponse"][];
      /**
       * Audit Logs
       * @description List of audit log entries
       */
      audit_logs?: components["schemas"]["AuditLogResponse"][];
    };
    /**
     * ModuleVersionStatusUpdate
     * @description Model for updating the status of a module version.
     *
     *     Attributes:
     *         status (WorkflowStatus): New workflow status to be set.
     *         comment (str | None): Optional reason for rejection or approval note.
     */
    ModuleVersionStatusUpdate: {
      /** @description New workflow status */
      status: components["schemas"]["WorkflowStatus"];
      /**
       * Comment
       * @description Reason for rejection or approval note
       */
      comment?: string | null;
    };
    /**
     * ModuleVersionUpdate
     * @description Model for updating a module version.
     *
     *     Attributes:
     *         content (str | None): Updated content of the module version.
     *         ects (int | None): Updated ECTS credits for the module version.
     *         valid_from_semester (str | None): Updated semester from which the module
     *             version is valid.
     */
    ModuleVersionUpdate: {
      /**
       * Content
       * @description Module version content
       */
      content?: string | null;
      /**
       * Ects
       * @description ECTS credits
       */
      ects?: number | null;
      /**
       * Valid From Semester
       * @description e.g. 'WiSe 2025/26'
       */
      valid_from_semester?: string | null;
    };
    /** PaginatedResponse[ModuleResponse] */
    PaginatedResponse_ModuleResponse_: {
      /** Data */
      data: components["schemas"]["ModuleResponse"][];
      meta: components["schemas"]["PaginationMeta"];
    };
    /** PaginatedResponse[UserResponse] */
    PaginatedResponse_UserResponse_: {
      /** Data */
      data: components["schemas"]["UserResponse"][];
      meta: components["schemas"]["PaginationMeta"];
    };
    /**
     * PaginationMeta
     * @description Metadata for pagination.
     *
     *     Attributes:
     *     ----------
     *     total : int
     *         Total number of items.
     *     page : int
     *         Current page number.
     *     limit : int
     *         Number of items per page.
     *     offset : int
     *         Number of items initially skipped.
     *     total_pages : int
     *         Total number of pages.
     */
    PaginationMeta: {
      /** Total */
      total: number;
      /** Page */
      page: number;
      /** Limit */
      limit: number;
      /** Offset */
      offset: number;
      /** Total Pages */
      total_pages: number;
    };
    /**
     * ReadyResponse
     * @description Represents the overall readiness status of the server.
     *
     *     Attributes:
     *     ----------
     *     status : Literal["pass", "fail"]
     *         The overall readiness status of the server, either "pass" or "fail".
     *     details : ReadyResponseDetails
     *         The status of individual dependencies (e.g., database).
     */
    ReadyResponse: {
      /**
       * Status
       * @description Overall readiness status (pass/fail)
       * @enum {string}
       */
      status: "pass" | "fail";
      /** @description Status of individual dependencies (e.g., database) */
      details: components["schemas"]["ReadyResponseDetails"];
    };
    /**
     * ReadyResponseDetails
     * @description Represents the details of the server's readiness status.
     *
     *     Attributes:
     *     ----------
     *     database : Literal["pass", "fail"]
     *         The status of database connectivity, either "pass" or "fail".
     */
    ReadyResponseDetails: {
      /**
       * Database
       * @description Database connectivity status
       * @enum {string}
       */
      database: "pass" | "fail";
    };
    /**
     * RunningResponse
     * @description Represents the server's running status.
     *
     *     Attributes:
     *     ----------
     *     status : Literal["pass", "fail"]
     *         The running status of the server, either "pass" or "fail".
     */
    RunningResponse: {
      /**
       * Status
       * @description Running status of the server
       * @enum {string}
       */
      status: "pass" | "fail";
    };
    /**
     * SortOrder
     * @description Enum for sort order.
     *
     *     This enum defines the possible sort orders for retrieving user data.
     * @enum {string}
     */
    SortOrder: "asc" | "desc";
    /**
     * Token
     * @description Represents an authentication token.
     *
     *     Attributes:
     *     ----------
     *     access_token : str
     *         The access token string.
     *     token_type : str
     *         The type of the token, e.g., "Bearer".
     */
    Token: {
      /** Access Token */
      access_token: string;
      /** Token Type */
      token_type: string;
    };
    /**
     * TranslationCreate
     * @description Model for creating a translation.
     *
     *     Attributes:
     *         language (str): Language code (e.g., 'en').
     *         title (str): Translated title.
     *         content (str): Translated content.
     */
    TranslationCreate: {
      /**
       * Language
       * @description Language code (e.g., 'en')
       */
      language: string;
      /**
       * Title
       * @description Translated title
       */
      title: string;
      /**
       * Content
       * @description Translated content
       */
      content: string;
    };
    /**
     * TranslationResponse
     * @description Response model for translations.
     *
     *     Attributes:
     *         id (uuid.UUID): Unique identifier for the translation.
     *         module_version_id (uuid.UUID): Associated module version ID.
     *         is_outdated (bool): Indicates if the translation is outdated.
     *         language (str): Language code (e.g., 'en').
     *         title (str): Translated title.
     *         content (str): Translated content.
     */
    TranslationResponse: {
      /**
       * Language
       * @description Language code (e.g., 'en')
       */
      language: string;
      /**
       * Title
       * @description Translated title
       */
      title: string;
      /**
       * Content
       * @description Translated content
       */
      content: string;
      /**
       * Id
       * Format: uuid
       * @description Unique identifier for the translation
       */
      id: string;
      /**
       * Module Version Id
       * Format: uuid
       * @description Associated module version ID
       */
      module_version_id: string;
      /**
       * Is Outdated
       * @description Indicates if the translation is outdated
       */
      is_outdated: boolean;
    };
    /**
     * UserCreate
     * @description Model for creating a new user.
     *
     *     This class defines the structure of the user data required for creating
     *     a new user.
     *
     *     Attributes:
     *         user_id (str): The unique identifier for the user.
     *         password (str): The password for the user.
     */
    UserCreate: {
      /**
       * Name
       * @description The username of the user
       */
      name: string;
      /** @description The faculty of the user */
      faculty: components["schemas"]["Faculty"];
      /** @description The role of the user */
      role: components["schemas"]["UserRole"];
      /**
       * User Id
       * @description The unique identifier for the user
       */
      user_id: string;
      /**
       * Password
       * @description The password for the user
       */
      password: string;
    };
    /**
     * UserFields
     * @description Enumeration of user fields for sorting and filtering.
     *
     *     This class defines the fields that can be used for sorting and filtering
     *     user data in queries.
     * @enum {string}
     */
    UserFields: "user_id" | "name" | "faculty" | "role";
    /**
     * UserPatch
     * @description Model for partially updating user data.
     *
     *     This class defines the structure of the user data that can be updated
     *     partially, with all fields being optional.
     *
     *     Attributes:
     *         name (str | None): The username of the user.
     *         faculty (Faculty | None): The faculty of the user.
     *         role (UserRole | None): The role of the user.
     *         password (str | None): The password for the user.
     */
    UserPatch: {
      /**
       * Name
       * @description The username of the user
       */
      name?: string | null;
      /** @description The faculty of the user */
      faculty?: components["schemas"]["Faculty"] | null;
      /** @description The role of the user */
      role?: components["schemas"]["UserRole"] | null;
      /**
       * Password
       * @description The password for the user
       */
      password?: string | null;
    };
    /**
     * UserResponse
     * @description Response model for user data.
     *
     *     This class defines the structure of the user data returned in API responses.
     *
     *     Attributes:
     *         user_id (str | None): The unique identifier for the user.
     *         name (str | None): The username of the user.
     *         faculty (Faculty | None): The faculty of the user.
     *         role (UserRole | None): The role of the user.
     */
    UserResponse: {
      /**
       * User Id
       * @description The unique identifier for the user
       */
      user_id?: string | null;
      /**
       * Name
       * @description The username of the user
       */
      name?: string | null;
      /** @description The faculty of the user */
      faculty?: components["schemas"]["Faculty"] | null;
      /** @description The role of the user */
      role?: components["schemas"]["UserRole"] | null;
    };
    /**
     * UserRole
     * @description Enumeration of user roles within the application.
     *
     *     Attributes:
     *     ----------
     *     MODULE_OWNER : str
     *         Represents a module owner.
     *     PROGRAM_COORDINATOR : str
     *         Represents a program coordinator.
     *     EXAMINATION_OFFICE : str
     *         Represents the examination office.
     *     DEANERY : str
     *         Represents the deanery.
     *     ADMIN : str
     *         Represents an server administrator.
     * @enum {string}
     */
    UserRole:
      | "MODULE_OWNER"
      | "PROGRAM_COORDINATOR"
      | "EXAMINATION_OFFICE"
      | "DEANERY"
      | "ADMIN";
    /**
     * UserUpdate
     * @description Model for updating user data.
     *
     *     This class defines the structure of the user data required for updating
     *     user information.
     *
     *     Attributes:
     *         name (str): The username of the user.
     *         faculty (Faculty): The faculty of the user.
     *         role (UserRole): The role of the user.
     *         password (str): The password for the user.
     */
    UserUpdate: {
      /**
       * Name
       * @description The username of the user
       */
      name: string;
      /** @description The faculty of the user */
      faculty: components["schemas"]["Faculty"];
      /** @description The role of the user */
      role: components["schemas"]["UserRole"];
      /**
       * Password
       * @description The password for the user
       */
      password: string;
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
    };
    /**
     * WorkflowStatus
     * @description Enumeration of workflow statuses within the application.
     *
     *     Attributes:
     *     ----------
     *     DRAFT : str
     *         Represents a draft status.
     *     IN_REVIEW : str
     *         Represents a status where the module is under review by the coordinator.
     *     VALIDATION_EO : str
     *         Represents a status where the module is being validated by the
     *         examination office.
     *     APPROVAL_DEANERY : str
     *         Represents a status where the module is awaiting approval from the
     *         deanery.
     *     RELEASED : str
     *         Represents a status where the module has been released.
     *     IN_REVISION : str
     *         Represents a status where the module is under revision.
     * @enum {string}
     */
    WorkflowStatus:
      | "DRAFT"
      | "IN_REVIEW"
      | "VALIDATION_EO"
      | "APPROVAL_DEANERY"
      | "RELEASED"
      | "IN_REVISION";
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  login_for_access_token_v0_auth_token_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/x-www-form-urlencoded": components["schemas"]["Body_login_for_access_token_v0_auth_token_post"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: Record<string, unknown>;
        content: {
          "application/json": components["schemas"]["Token"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: Record<string, unknown>;
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  check_running_v0_health_running_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: Record<string, unknown>;
        content: {
          "application/json": components["schemas"]["RunningResponse"];
        };
      };
    };
  };
  check_ready_v0_health_ready_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: Record<string, unknown>;
        content: {
          "application/json": components["schemas"]["ReadyResponse"];
        };
      };
    };
  };
  get_all_users_v0_users__get: {
    parameters: {
      query?: {
        /** @description Filter by faculty */
        faculty?: components["schemas"]["Faculty"] | null;
        /** @description Filter by role */
        role?: components["schemas"]["UserRole"] | null;
        /** @description Search by name */
        search?: string | null;
        /** @description Field to sort by (user_id, name, faculty, role) */
        sort_by?: components["schemas"]["UserFields"];
        /** @description Sort order (asc or desc) */
        sort_order?: components["schemas"]["SortOrder"];
        /** @description Page number for pagination */
        page?: number;
        /** @description Number of items per page */
        limit?: number;
        /** @description Number of items to skip */
        offset?: number;
        /**
         * @description [
         *       "Comma-separated list of fields to include in the response",
         *       "(e.g. 'user_id,name')"
         *     ]
         */
        fields?: string | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: Record<string, unknown>;
        content: {
          "application/json": components["schemas"]["PaginatedResponse_UserResponse_"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: Record<string, unknown>;
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  create_user_v0_users__post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UserCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: Record<string, unknown>;
        content: {
          "application/json": components["schemas"]["UserResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: Record<string, unknown>;
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_user_v0_users__id__get: {
    parameters: {
      query?: {
        /**
         * @description [
         *       "Comma-separated list of fields to include in the response",
         *       "(e.g. 'id,name')"
         *     ]
         */
        fields?: string | null;
      };
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: Record<string, unknown>;
        content: {
          "application/json": components["schemas"]["UserResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: Record<string, unknown>;
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  update_user_v0_users__id__put: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UserUpdate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: Record<string, unknown>;
        content: {
          "application/json": components["schemas"]["UserResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: Record<string, unknown>;
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  delete_user_v0_users__id__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: Record<string, unknown>;
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: Record<string, unknown>;
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  patch_user_v0_users__id__patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UserPatch"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: Record<string, unknown>;
        content: {
          "application/json": components["schemas"]["UserResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: Record<string, unknown>;
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_all_modules_v0_modules__get: {
    parameters: {
      query?: {
        /** @description Filter by faculty */
        faculty?: components["schemas"]["Faculty"] | null;
        /** @description Filter by owner ID */
        owner_id?: string | null;
        /** @description Filter by current version status */
        status?: components["schemas"]["WorkflowStatus"] | null;
        /** @description Search in title or number */
        search?: string | null;
        /** @description Field to sort by */
        sort_by?: components["schemas"]["ModuleFields"];
        /** @description Sort order */
        sort_order?: components["schemas"]["SortOrder"];
        /** @description Page number */
        page?: number;
        /** @description Items per page */
        limit?: number;
        /** @description Number of items to skip */
        offset?: number;
        /**
         * @description [
         *       "Comma-separated list of fields to include in the response",
         *       "(e.g. 'id,module_number,title')"
         *     ]
         */
        fields?: string | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: Record<string, unknown>;
        content: {
          "application/json": components["schemas"]["PaginatedResponse_ModuleResponse_"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: Record<string, unknown>;
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  create_module_v0_modules__post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ModuleCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: Record<string, unknown>;
        content: {
          "application/json": components["schemas"]["ModuleResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: Record<string, unknown>;
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_module_v0_modules__module_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        module_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: Record<string, unknown>;
        content: {
          "application/json": components["schemas"]["ModuleResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: Record<string, unknown>;
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_module_versions_v0_modules__module_id__versions_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        module_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: Record<string, unknown>;
        content: {
          "application/json": components["schemas"]["ModuleVersionResponse"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: Record<string, unknown>;
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_version_v0_modules_versions__version_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        version_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: Record<string, unknown>;
        content: {
          "application/json": components["schemas"]["ModuleVersionResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: Record<string, unknown>;
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  update_version_content_v0_modules_versions__version_id__put: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        version_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ModuleVersionUpdate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: Record<string, unknown>;
        content: {
          "application/json": components["schemas"]["ModuleVersionResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: Record<string, unknown>;
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  update_workflow_status_v0_modules_versions__version_id__status_patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        version_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ModuleVersionStatusUpdate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: Record<string, unknown>;
        content: {
          "application/json": components["schemas"]["ModuleVersionResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: Record<string, unknown>;
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  add_translation_v0_modules_versions__version_id__translations_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        version_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["TranslationCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: Record<string, unknown>;
        content: {
          "application/json": components["schemas"]["TranslationResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: Record<string, unknown>;
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
}
